version: '3.8'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n-server
    restart: always
    ports:
      - "5678:5678"
    environment:
	- N8N_HOST=localhost
      	- N8N_PORT=5678
      	- N8N_PROTOCOL=http
      	- GENERIC_TIMEZONE=Asia/Kolkata
      	- WEBHOOK_URL=https://buena-aurorean-unstatuesquely.ngrok-free.dev/workflow/OySwTle0jUMaf0Lk/dc2f18
     volumes:
      - n8n_data:/home/node/.n8n
    # The --tunnel command creates a free, temporary HTTPS URL for Telegram
    command: start --tunnel

volumes:
  n8n_data: